### ISSUE TITLE
Error: Missing key(s) in state_dict: "position_enc.weight"

### ISSUE THREAD

**Issue by ChuanMeng** [suchanadatta/qppBERT-PL#2]
Hi,
When I'm loading the checkpoint released by this repo, I encounter the error: Missing key(s) in state_dict: "position_enc.weight".
I speculate that the code in this repo and the released checkpoint don't match. I would appreciate it if you could check it?

![image](https://user-images.githubusercontent.com/37291827/200611394-2275b868-6446-469c-b734-0b7bab888c9d.png)

Best wishes,
Chuan

**Comment by suchanadatta** [comment]
Hi,
That is because the checkpoint you are using at the moment doesn't incorporate position embeddings. You can simply turn off position embeddings in the code (all about passing parameters accordingly) and you are good to go. I will share the checkpoint that combines position too in the repo. Any help required in changing codes, just let me know.

Bests,
Suchana

**Comment by ChuanMeng** [comment]
Thank you Suchana. Looking forward to the checkpoint that combines positions.

Best wishes,
Chuan
